/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webullmodel
// Order struct for Order
type Order struct {
	// Example: 'option'
	ComboTickerType string `json:"combo_ticker_type,omitempty"`
	Legs []Leg `json:"legs,omitempty"`
	StatusCode string `json:"status_code,omitempty"`
}
