/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webullmodel
// GetFundamentalsResponseLabels struct for GetFundamentalsResponseLabels
type GetFundamentalsResponseLabels struct {
	Key string `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
}
