/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webullmodel
// PostLoginResponseExtInfo struct for PostLoginResponseExtInfo
type PostLoginResponseExtInfo struct {
	UserPwdFlag string `json:"userPwdFlag,omitempty"`
}
