/*
 * Webull API
 *
 * Webull API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webullmodel
// Direction the model 'Direction'
type Direction string

// List of Direction
const (
	DEBIT Direction = "debit"
	CREDIT Direction = "credit"
)
